language: java
jdk:
- openjdk8
dist: bionic
notifications:
  email:
    recipients:
    - dev@dattack.com
    on_success: always
    on_failure: always
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: oCm6gjSGB7x0bdqv/i/CwSwGPvrommZt6RuKLjNAOq8g8fEUmN7woUhCUboVBSF7yZVTkTDgwhKKdwIp0pqbIzvVKavXLVmBOEJicIwev4SOcF9H2LG8e5HpFAA9hcxeyntj8mfpzqA5vAN/VN43mKTr1Fq7TfhAhNm0JaH2netnhF5MQ4Ra8F0gONHF73N9AFrY+YtvFDt6ENX5l8lXRUIhC4npoa9y/XcoU4mlAg+JF3tdQJ1iZZjFVTF4HXWpKD/f7LVjRyoc4Mqs9OIL6L//3wBawOFHjEWgo8qGoUuSQvW9PCpGGIGkmm0z7BL80utm77E+lkW520yfI0n8aHeYBrV+o9oKZovVHm9FIZ6gbi6uwOkzmitFFoCcR4L3wC5xYlx/k4x5zlzvIhAQg7Q9RSuiSkfhglg73W88oJpbvxY76cByHjjBucH+fs3Tk6obR9blQDFb6SuC4iy5FIw7qU2U+2UpanCWEPIzoqZMEvhfM6CI8Bz7kYnCJPGHVsXy6ncBgVbcBavhN46vnBCjcXkZs602jB5cbjYU9id2NSwXWwQg/8m3Ok/mFqb2pPCEilwlkTPyh9a08FDcuf6KJYhZ6G9AyzMheQqvzTpHBdmySYzCgwxW5tJKwKVcYt+EJbkKGnIRHMXMZ4jU4REg3nRyZkOZORjEZ/SqRPE=
  - secure: cLkDzMVQErHqh7QUCtIaiImPsPt9OwNBgABrp6OGUBuHY08+cg19NSWx8QdMdV/CFZziOYpFPEtBqrtBOYmegpa9bWOHZMnSMjjaEJf1Wmd/6DmFva4xnCMaL7ANr4Uqqz1glsUeM8WRV8bMtyimID2k5wUHQMlQdwD9lE9NBJuHb2pjJaID3wbGmVqzlfTWHDcP/eG9aAs5VwCARV633VZkiauN7YX6RDUrcLR7QGepIWJuHY2EKVQcDdn3z8QIUzLGLiUMJfLQWyBm+Jshs9Xh4lv2xKsQSa7kAZD7cwtlC+DUn7OxZs1CZ8uu2ybtNmQTbhZSPA1FSXUAFM1wXNY/5PjCdrnzuQfas5caVAB+ruz3764+eTSQPjvoDyzdlVPEb10GuLt4phXv1HIb5Lnt18eO8UMc8i59iZLWIMFUaJiVuETgQWhgWys+H2p6PGTCfrDb9tcRsPj1H/Zc58jJov93ATuIBGv2NMxB3mCJPxsoXCzJrH4XTy1vYEyiE6piZJc5ZA3PEOXcrIx/F4Xn8fuwYboDfIiRATU8nQz3wX5el6HBlcM+k7EAnkTEZuEAvc1LDKWXfDT0wvoqG1MCinJzbEKMQX4r3tCDTcklFF/1axDWtoz0L0FiOKhgGzql20iLKmL5rUwhflGiZf0ZN0NzzvcRUuMgArC4Pkw=
  - secure: kMpN3E6V665pnjtkHRErXH+rQ+iexwn/MRA3HbV90oWprO0pa+/tiH0f8a+wQa8h6cdv7Ifiv484SNGo5CTOlncOzLG5y/I/6RQ6t9ayiOLqQ891Zaxeg3uQmYQzP5BcW6MzsvGM4ybGAIFQoga46pyBw19Nk1chwOTkq/arlpPaEqfiBa2oD8n7Xm1P1EPT+pIsnJ8zvE1n0TtVM6FPrIagWAkToqseqC6HWoRDGpfne++a6aa8q0JOPTHaJU2H3mmh190tinO9X/4GM7Bd0m1hIp5UlZdmCCWmfk0Hw9WKodk1SS9uJ2WVxdeeFEQmt727puJa2E4fhnNhqXzlvtSj2TRQIaOuyXyoGUjlfMAvYjwhutHgt8/RRhLQ8OBPqLG00iSxpI8OvrAicdstqPVEPVL/Kp8ntQtNa880W+0WnX2S/21b97Kke8Rj2obwnVejPwWLGXoNR/t36wqg5i2hcRhyXzMqhUMEpucyQ7kOdvPpncyLC8Mv3cKzvH9r5tP3f4zD/VsM3bP6YM7iZzr7C9SVThSttTXz4bu74NOWq0cfOp6TSj9hCovlJf17OdITPtpr9XXudHvySA3na047I9Eyd3xpVZoLUM2XfZMnuZ4D1Zh+hF7gDXGAPgi5oHxs9DgY7Dbvx5rBXdH/3Wu0GNbT5OFMjvIZ35ktJ/M=
  - secure: hGG4FtcwPxtqIXeb3YsowCgPPKQcFSi63nznArCD04le4T7tRXirQJwMmsPI5g0s3jsQdJfTENC5j3NdCgAMtIZEPsZO0HSm3A55eeyypPE1YBKfVT7ThPSDy6OQQP45xbI4UO39LwlmRTC874QVZoJar//3Ji6xFvbAfZsiEEdtcaUXO06kI9Fmpdh3PsKUgvgPteUdwJQfu9zTpYfYYtRA1FKnp6qhV9/EaBFEqNVrw8yTFo2/uiCds/xi7/czEtgUlt+n+xdTcK3ghEDccpWtVmtF51MSSrL2idrz7u6KBX89OTibHQEXcSfSUdlQ9AyRE5ixWMTDT0vsubiz9Vo2VXuybmubWrfRrlV4g4MzmenoF4R24h9jS60wQ+emZkBTLTv17iI1Iasn3tmLcVsc1Dj4fyXzBJvqgSlWRQ85o0Qe1lIpUAUFWwF5VmHUn3bMH61tRtCn69PJ+9VUfb9/PrmfZwADG62oTPDlHWUkYcSia9CZSHGIB0i6NRn+oqwLb5EaM6TDzIMMQkmJu5BboQoBHn7ZhMI5EBnVP3un9g33pNxin/kzP+zL3OFSYlLLZy+w4tAtQQLb/afe2QrnDudB7zVlXON2it3f3shS9Fk5jqyD0cNbG9JedihB1XDKdt32ksAuyqMnSrofwKNwr1uml3uhVGMLjdbpPQY=
install: mvn -P !build-extras install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -P !build-extras test -B
before_deploy:
- openssl aes-256-cbc -K $encrypted_711e5bbf5b76_key -iv $encrypted_711e5bbf5b76_iv
  -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
- gpg --batch --fast-import .travis/codesigning.asc
deploy:
  skip_cleanup: true
  provider: script
  script: mvn -P sign,build-extras -s .travis/settings.xml deploy -DskipTests
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^(master|develop)$"
