language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - dev@dattack.com
    on_success: always
    on_failure: always
env:
  global:
  - secure: V1viIVEIn9VCZsP3XClkJeH6JFByxsZwMsVdiFTqywD3y/0poJusbpf3GgmBZK4IZ/9h1nfRYS0V7sJuAdKY4Ea2Zp5VQVIrEjfWb9laVcL9Z0Crel8FHuGgIQiMHnPm4PHQeDZraeZ/JBesNIQMSLp2puokIJwCA5kBiGXqUEHgGKrWB2Dnv7o2/4jm3YK0O9YM0rQFnjJhPfLomoGdDh4cvexX20i3ivesfZ47V8zUCx85yYHTPfB+ECUaEHDqzhPG318DYVwVucTpK5ejvoOI0i7TToXjIVXiH2ZUMk/gkkvcAhLJTjZLDUpUFjwTJJIMx6iwVDRNw7GpzJKnNdkf8rLHZ0zOh1ooY+IGpP6Fjsvr/0kG3n+My6aZLImD4nglRGdTmhyWU4rifPonys8ZzMaGejTQ7sayeVP1OJeZWYbYuwPjlw9g3sW1LQlBfx5XlhIcyv5gtTVetnQ7SD+r1YwMQmBDYuZfCDj1cnayjeEqA1kjlzHuEwuAFZU/b7OTczp6+2EGeFC9sRXMS/q5lQM3jFQnAJNsYPRTXdalI1y/E+tij4gNoz/ETZ3BljepGMrbSQlDuGqdWoNwBa8/eD1dXBeetFrhNukkVtKRghg0LkYYSq3y+26SQd0dy+Zb6wYylcoVL4gJO/6IrUCkCGBDs/YWHrMPByvMZp4=
  - secure: mnZ9QUc02p7IPvxJ9GqoWqWH+IEaPENcZ1PPgEfU07CKjDyXbJARm2SgA+bVcERlRTvhErCRxc9O7S2TX7cgHSwFDx1vQYHWYRPtY2IAm7hisvo59sbppWlDFDUDU1Ndv/73qRsEYANIFsK3T1lvWSDgr4/WofctG60+jXXuy//85xNpKi/49FFNFKdTYb1IsWFI3aw8fDEwKuHCSS6oCfVH4woNu9ApoI9r2Qiz6X0crbg/bmk/iDgYQTsJxHDnjHwvpgUv090Go0EbkG8sp191JAtlN94cdgAWWD/UUrmOIaCXuhWfDFnsIjMLyZJ8G9VYtJM32YAS6KO/5RK+Ir1q146DMBg/eqr/mdv9a2UHXysIZVFl7eCpAl8SPJdw0OacODSyncyyIeATL7x/Aop1E1kPKaqQtCIGSxo2XhXRPnD09qO2Z878XJpl9AYcEywIFeYNWd9571kDPW+a6BRVSQTEqKluTuFAQ6XmUSBdpfITaBEwZI0fi8KXWK/m+JtANI5sPtSKOJBq8Bd2uSNGX6247ybd4dwgCbNMcxSa4sylIOgWq8iEx8PSRYJPBZec3NX7CyQf1jmdpoYvTyIYlrmXj7ANevud+tidY54//cpGVqw/5hQC6VTLCC6ZWNCIJmyYCqrIFxqDetC1H+dVa7Wr3ZKeZWflVJqPuC0=
  - secure: Uc837M+r9+7G+r+HrTQDkzJX0gRaJM8DU2KifhKaakeeQmhAHWLAFSzEHuWxdltC8Mc8vtDFHNC6j+COxX1LlM6SngcGq+K154BhYSADKSFJhHHtzJK4tposaCIzKysC0CisHLYA1OwwMoinDqtih325msfJisiAS6ZG4xtY5sTe36Q/5QdfRvgUu6B6AzDlNEjitVEXLT1rhkVZi7Mn2BgvohR5UMfTWxx1CnRChWwWQS6H/9n6qLsVg+vmgez/+uJ9hyQyQeJNfqdQJoDG5WHmn0JVYI+Y1pFqi6AVKNSSZlW+Hdak9FMaBMiKdSbETEJTireYBsRSLXKBh57KqmPrRAVC5f8RZruEuTEFrlTCEUlGMSoCp7ryFy106QiKfn7oFIOC0hNT5OPEdVOlFrJn2iBPdWTKgxDIzyD4ha3hZuBLpvsHhhxJBFqM/K0kP/u/muALyVpwUpDqEKtbJIL0feHsFmU/OHsxdw6AoHedj/75SvwG48Rz3bZxlTX3mR7xOs8Y/URWrw8EcV6JAq+HcRwsvcfWFDwTSGQmq0ponbgUcOU0Icd26yYNPwwCRJXl+leQrMYiFKqPPIdioqKSTbRKisxil+rgbNku42nPUQE8LJ5oBu2wEtQ04l/x2hncumAGLN+ZRyy7c8KjQCnrKWgYnRc5EaDbm0NtIj4=
  - secure: EkxFyttfd2/pqph/PUzJ/92TLAdnJU4Bd0s+oEIX4XGjZxmQn0n3fq16oCIl6FdL2fuMqtw7xcLfcAw7SZsseuDcHC6hdQCdXoHvhAzedFxbo/KwbStyfnrXpTopjEMGsdlCsxPoOSAaUHvMqD1EFKCLeqMKQ+iM6hE7VCNwR5AgLR2sRVt9ZNHIeDmw64B6iRizQPQDpRkjfGKX9qvSxfzHK+G3munkwnUlQUKvD/lqqa910z+RG2SslnV9322uYF+IgbHfn99nciQnTuyNJiRJLxixpUKFwxF4yIHHmT0U736LruA0KkhuCiuN3Iw2D/wM9GEAJGfEkGexCyABiqKlJZw8WoFohnXmoOaA8g7XFtjKnVGWMf9f8sxKYDb9tojlFdabbz+L8bsvuPSklWTECnYGoHYQ5ugnJJBQg8fY5xnsgztk0FJlBlZRsF1+flBOMTkXi6THM9oN00wCpsuur0mhN2KBdP9G7rJ+QsYtgEBTRnPqsje1hByWqmidV9cqQIwYqce5Zi3tw10nZOY5gyYH4iuSiq+/xhisM2wP9Qp8dkfAPDaz9LXihK583HwQeEMEW7367DUcblDxfsfvbvG5UgCBnuMzCwxvO85Cjp4CNRXM96tNlJ/7J2VewHePk5NBHlnZuT6Xa2rbAR6GU99kcsNBgHFb06S8O0Y=

install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn test -P !build-extras -B

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./.travis/before-deploy.sh
  - ./.travis/deploy.sh
